import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
  en: {
    translation: {
      nav: { home: "Home", about: "About", features: "Features", howItWorks: "How It Works", diseases: "Diseases", testimonials: "Testimonials", download: "Download App" },
      hero: { tag: "✨ The Future of Farming", title1: "Smart AI for", title2: "Modern Farmers", desc: "Instantly detect crop diseases, get expert treatments, and manage your farm smartly with the Krushi Sathi AI App. Designed for the Indian farmer.", downloadBtn: "Download App", learnBtn: "Learn More", stats: { farmers: "Farmers", accuracy: "Accuracy", crops: "Crops" } },
      features: { tag: "Powerful Features", title: "Everything you need to grow better", desc: "Krushi Sathi is packed with intelligent tools designed specifically to help farmers increase yield and reduce losses.", items: { scanTitle: "AI Crop Scanning", scanDesc: "Take a photo of a sick leaf and instantly get the disease name, severity, and accurate treatment recommendations.", expertTitle: "Expert Q&A", expertDesc: "Connect directly with agricultural experts. Ask questions, share photos, and get personalized farming advice.", weatherTitle: "Smart Weather Forecast", weatherDesc: "Hyper-local weather forecasts tailored for your farm to help you plan sowing, irrigation, and harvesting.", fertTitle: "Fertilizer Guide", fertDesc: "Calculate the exact amount of NPK and micronutrients required for your specific crop and soil type.", alertTitle: "Timely Alerts", alertDesc: "Receive push notifications for weather warnings, disease outbreaks in your area, and spray reminders.", secTitle: "Secure & Private", secDesc: "Your farm data is encrypted and secure. We respect your privacy and only use data to improve your yields." } },
      hiw: { tag: "Simple Process", title: "How Krushi Sathi Works", desc: "Detecting crop diseases has never been this easy. Just snap a photo and let our AI do the heavy lifting for you.", s1t: "Open the Scanner", s1d: "Launch the Krushi Sathi app and tap the AI Scan button from your dashboard.", s2t: "Take a Photo", s2d: "Point your camera at the infected crop leaf. Ensure the leaf is clearly visible and in focus.", s3t: "Get Instant Analysis", s3d: "Our AI instantly analyzes the image, identifies the disease, and provides a severity score.", s4t: "Apply Treatment", s4d: "Follow the recommended organic or chemical treatment plans to save your crop and improve yield." },
      diseases: { tag: "Crop Library", title: "Common Diseases We Detect", desc: "Our AI model is trained on millions of images to identify over 100+ diseases across 30+ crops accurately.", btn: "View Full Library", learn: "Learn Treatment" },
      testimonials: { tag: "Trusted by Thousands", title: "What Farmers Say", desc: "Join over 50,000 farmers who trust Krushi Sathi to protect their crops and boost their income.", reviews: [{name: "Ramesh Patil", loc: "Maharashtra", text: "Krushi Sathi app saved my tomato crop this year. I took a photo of the sick leaf and it instantly told me it was Early Blight and gave me the exact medicine name. Highly recommended!"},{name: "Suresh Kumar", loc: "Punjab", text: "The fertilizer guide is amazing. Instead of guessing, I now know exactly how much Urea and DAP to use for my wheat farm. My yield has increased by 20%!"},{name: "Anil Deshmukh", loc: "Gujarat", text: "Asking questions to experts directly from the app is the best feature. The doctors reply quickly with practical solutions that actually work in the field."}] },
      cta: { title: "Ready to transform your farming?", desc: "Download the Krushi Sathi app today and join the community of modern farmers leveraging AI to increase their crop yield.", btn1: "Download App Now", btn2: "Contact Expert" },
      footer: { desc: "Empowering the modern Indian farmer with Artificial Intelligence. Smart disease detection, weather updates, and expert farming advice right in your pocket.", prod: "Product", comp: "Company", legal: "Legal", f1: "Features", f2: "How it Works", f3: "Crop Library", f4: "Pricing", c1: "About Us", c2: "Careers", c3: "Contact", c4: "Partners", l1: "Privacy Policy", l2: "Terms of Service", l3: "Cookie Policy", copy: "Krushi Sathi AI. All rights reserved." },
      about: { tag: "Our Mission", title: "Empowering the Modern Farmer", desc: "Krushi Sathi was built with a single goal: to bring world-class agricultural AI technology to the fingertips of every farmer in India. We believe that technology should be accessible, affordable, and practical.", cards: [{title: "Sustainable Farming", desc: "Promoting organic solutions and optimal fertilizer usage."}, {title: "Data Security", desc: "Your farm data is encrypted and completely private."}, {title: "Expert Community", desc: "Connecting you with certified agricultural scientists."}] },
      pricing: { tag: "Pricing", title: "Simple, Transparent Pricing", desc: "Start for free and upgrade when you need more advanced AI tools and expert consultations.", basic: { name: "Basic Plan", desc: "Perfect for small-scale farmers.", f1: "5 AI Crop Scans / month", f2: "Basic Weather Alerts", f3: "Community Access Only", btn: "Get Started Free" }, pro: { name: "Pro Farmer", desc: "For commercial farming and max yield.", f1: "Unlimited AI Scans", f2: "Premium Weather & Pest Alerts", f3: "Direct Expert Consultation (Voice/Video)", f4: "Fertilizer Calculator", btn: "Upgrade to Pro", rec: "RECOMMENDED" } },
      contact: { title: "Contact Us", name: "Name", email: "Email", msg: "Message", btn: "Send Message" },
      privacy: { title: "Privacy Policy", d1: "1. Data Collection", p1: "We collect images of crops that you submit for AI analysis. These images are securely processed and used strictly for identifying crop diseases. We may also collect your phone number and location if you opt-in to weather alerts.", d2: "2. Data Usage", p2: "Your data is never sold to third parties. We use crop data anonymously to improve our AI models and provide accurate agricultural insights.", d3: "3. Security", p3: "We employ industry-standard security measures to ensure your personal information remains safe on our servers." },
      terms: { title: "Terms of Service", t1: "1. Acceptance of Terms", p1: "By using the Krushi Sathi application, you agree to these Terms of Service. If you do not agree, please do not use our services.", t2: "2. Use of Service", p2: "Our AI models provide recommendations based on image analysis. While highly accurate, they are not a substitute for professional in-person agricultural assessment. We are not liable for crop loss resulting from AI misdiagnosis.", t3: "3. User Conduct", p3: "You agree not to misuse the service by submitting irrelevant images, spamming expert consultations, or attempting to breach our security." }
    }
  },
  mr: {
    translation: {
      nav: { home: "मुख्यपृष्ठ", about: "आमच्याबद्दल", features: "वैशिष्ट्ये", howItWorks: "हे कसे काम करते", diseases: "रोग", testimonials: "अभिप्राय", download: "अॅप डाउनलोड करा" },
      hero: { tag: "✨ शेतीचे भविष्य", title1: "आधुनिक शेतकऱ्यांसाठी", title2: "स्मार्ट AI", desc: "कृषी सार्थी AI अॅपद्वारे पिकांच्या रोगांची त्वरित नोंद घ्या, तज्ञांचे उपचार मिळवा आणि आपली शेती स्मार्टपणे व्यवस्थापित करा. भारतीय शेतकऱ्यांसाठी डिझाइन केलेले.", downloadBtn: "अॅप डाउनलोड करा", learnBtn: "अधिक जाणून घ्या", stats: { farmers: "शेतकरी", accuracy: "अचूकता", crops: "पिके" } },
      features: { tag: "प्रबळ वैशिष्ट्ये", title: "चांगली वाढ करण्यासाठी आवश्यक सर्व काही", desc: "कृषी सार्थी मध्ये शेतकऱ्यांचे उत्पन्न वाढवण्यासाठी आणि नुकसान कमी करण्यासाठी खास डिझाइन केलेली स्मार्ट साधने आहेत.", items: { scanTitle: "AI पीक स्कॅनिंग", scanDesc: "आजारी पानाचा फोटो काढा आणि लगेच रोगाचे नाव, तीव्रता आणि अचूक उपचारांच्या शिफारसी मिळवा.", expertTitle: "तज्ञ प्रश्नोत्तरे", expertDesc: "कृषी तज्ञांशी थेट संपर्क साधा. प्रश्न विचारा, फोटो शेअर करा आणि वैयक्तिकृत शेती सल्ला मिळवा.", weatherTitle: "स्मार्ट हवामान अंदाज", weatherDesc: "पेरणी, सिंचन आणि कापणीची योजना आखण्यासाठी आपल्या शेतासाठी अति-स्थानिक हवामान अंदाज.", fertTitle: "खत मार्गदर्शक", fertDesc: "तुमच्या विशिष्ट पिकासाठी आणि मातीच्या प्रकारासाठी आवश्यक NPK आणि सूक्ष्म अन्नद्रव्यांची अचूक मात्रा मोजा.", alertTitle: "वेळेवर सूचना", alertDesc: "तुमच्या भागातील हवामानाच्या इशाऱ्यांसाठी, रोगाच्या प्रादुर्भावासाठी आणि फवारणीच्या स्मरणपत्रांसाठी सूचना मिळवा.", secTitle: "सुरक्षित आणि खाजगी", secDesc: "तुमचा शेतीचा डेटा कूटबद्ध आणि सुरक्षित आहे. आम्ही तुमच्या गोपनीयतेचा आदर करतो आणि डेटा केवळ तुमचे उत्पन्न सुधारण्यासाठी वापरतो." } },
      hiw: { tag: "सोपी प्रक्रिया", title: "कृषी सार्थी कसे काम करते", desc: "पिकांचे रोग ओळखणे यापूर्वी इतके सोपे कधीच नव्हते. फक्त एक फोटो काढा आणि आमचे AI तुमचे काम करेल.", s1t: "स्कॅनर उघडा", s1d: "कृषी सार्थी अॅप सुरू करा आणि डॅशबोर्डवरून AI स्कॅन बटणावर टॅप करा.", s2t: "फोटो काढा", s2d: "तुमचा कॅमेरा संक्रमित पिकाच्या पानावर ठेवा. पान स्पष्टपणे दिसत असल्याची खात्री करा.", s3t: "त्वरित विश्लेषण मिळवा", s3d: "आमचे AI त्वरित प्रतिमेचे विश्लेषण करते, रोग ओळखते आणि तीव्रतेचा स्कोअर प्रदान करते.", s4t: "उपचार लागू करा", s4d: "तुमचे पीक वाचवण्यासाठी आणि उत्पादन वाढवण्यासाठी शिफारस केलेल्या सेंद्रिय किंवा रासायनिक उपचार योजनांचे अनुसरण करा." },
      diseases: { tag: "पीक लायब्ररी", title: "आम्ही शोधत असलेले सामान्य रोग", desc: "आमच्या AI मॉडेलला ३०+ पिकांवरील १००+ हून अधिक रोग अचूकपणे ओळखण्यासाठी लाखो प्रतिमांवर प्रशिक्षित केले आहे.", btn: "पूर्ण लायब्ररी पहा", learn: "उपचार शिका" },
      testimonials: { tag: "हजारो शेतकऱ्यांचा विश्वास", title: "शेतकरी काय म्हणतात", desc: "५०,००० पेक्षा जास्त शेतकऱ्यांमध्ये सामील व्हा जे त्यांच्या पिकांचे संरक्षण करण्यासाठी आणि उत्पन्न वाढवण्यासाठी कृषी सार्थीवर विश्वास ठेवतात.", reviews: [{name: "रमेश पाटील", loc: "महाराष्ट्र", text: "कृषी सार्थी अॅपने यावर्षी माझे टोमॅटोचे पीक वाचवले. मी आजारी पानाचा फोटो काढला आणि त्याने मला लगेच सांगितले की हे अर्ली ब्लाइट आहे आणि मला अचूक औषधाचे नाव दिले. नक्की वापरा!"},{name: "सुरेश कुमार", loc: "पंजाब", text: "खत मार्गदर्शक अद्भुत आहे. आता मला गव्हाच्या शेतासाठी किती युरिया आणि डीएपी वापरायचे हे अचूक माहीत आहे. माझे उत्पन्न २०% वाढले आहे!"},{name: "अनिल देशमुख", loc: "गुजरात", text: "अॅपवरून तज्ञांना थेट प्रश्न विचारणे हे सर्वोत्तम वैशिष्ट्य आहे. डॉक्टर लवकरच व्यावहारिक उपाय देतात जे प्रत्यक्षात शेतात काम करतात."}] },
      cta: { title: "तुमची शेती बदलण्यासाठी तयार आहात?", desc: "आजच कृषी सार्थी अॅप डाउनलोड करा आणि पिकाचे उत्पादन वाढवण्यासाठी AI चा लाभ घेणाऱ्या आधुनिक शेतकऱ्यांच्या समुदायात सामील व्हा.", btn1: "आता अॅप डाउनलोड करा", btn2: "तज्ञांशी संपर्क साधा" },
      footer: { desc: "आर्टिफिशियल इंटेलिजन्ससह आधुनिक भारतीय शेतकऱ्याचे सक्षमीकरण. स्मार्ट रोग शोध, हवामान अद्यतने आणि तज्ञांचा शेती सल्ला आपल्या खिशात.", prod: "उत्पादन", comp: "कंपनी", legal: "कायदेशीर", f1: "वैशिष्ट्ये", f2: "हे कसे काम करते", f3: "पीक लायब्ररी", f4: "किंमत", c1: "आमच्याबद्दल", c2: "करिअर", c3: "संपर्क", c4: "भागीदार", l1: "गोपनीयता धोरण", l2: "सेवा अटी", l3: "कुकी धोरण", copy: "कृषी सार्थी AI. सर्व हक्क राखीव." },
      about: { tag: "आमचे ध्येय", title: "आधुनिक शेतकऱ्याचे सक्षमीकरण", desc: "कृषी सार्थी एकाच ध्येयाने तयार केले गेले आहे: भारतातील प्रत्येक शेतकऱ्याच्या बोटांच्या टोकावर जागतिक दर्जाचे कृषी AI तंत्रज्ञान आणणे. आमचा विश्वास आहे की तंत्रज्ञान सुलभ आणि परवडणारे असावे.", cards: [{title: "शाश्वत शेती", desc: "सेंद्रिय द्रावणे आणि इष्टतम खत वापरास प्रोत्साहन देणे."}, {title: "डेटा सुरक्षा", desc: "तुमचा शेतीचा डेटा कूटबद्ध आणि पूर्णपणे खाजगी आहे."}, {title: "तज्ञ समुदाय", desc: "तुम्हाला प्रमाणित कृषी शास्त्रज्ञांशी जोडत आहे."}] },
      pricing: { tag: "किंमत", title: "सोपी, पारदर्शक किंमत", desc: "विनामूल्य सुरू करा आणि जेव्हा तुम्हाला अधिक प्रगत AI साधने आणि तज्ञांच्या सल्ल्याची आवश्यकता असेल तेव्हा अपग्रेड करा.", basic: { name: "मूळ योजना", desc: "लहान प्रमाणावरील शेतकऱ्यांसाठी योग्य.", f1: "दरमहा ५ AI पीक स्कॅन", f2: "मूलभूत हवामान सूचना", f3: "फक्त समुदाय प्रवेश", btn: "विनामूल्य सुरू करा" }, pro: { name: "प्रो शेतकरी", desc: "व्यावसायिक शेती आणि जास्तीत जास्त उत्पादनासाठी.", f1: "अमर्यादित AI स्कॅन", f2: "प्रीमियम हवामान आणि कीटक सूचना", f3: "थेट तज्ञ सल्लामसलत (व्हॉइस/व्हिडिओ)", f4: "खत कॅल्क्युलेटर", btn: "प्रो वर अपग्रेड करा", rec: "शिफारस केलेले" } },
      contact: { title: "आमच्याशी संपर्क साधा", name: "नाव", email: "ईमेल", msg: "संदेश", btn: "संदेश पाठवा" },
      privacy: { title: "गोपनीयता धोरण", d1: "1. डेटा संकलन", p1: "AI विश्लेषणासाठी तुम्ही सबमिट केलेल्या पिकांच्या प्रतिमा आम्ही संकलित करतो. या प्रतिमांवर सुरक्षितपणे प्रक्रिया केली जाते आणि पिकांचे रोग ओळखण्यासाठी काटेकोरपणे वापरले जाते.", d2: "2. डेटा वापर", p2: "तुमचा डेटा कधीही तृतीय पक्षांना विकला जात नाही. आमचे AI मॉडेल सुधारण्यासाठी आणि अचूक कृषी अंतर्दृष्टी प्रदान करण्यासाठी आम्ही पीक डेटाचा अनामिकपणे वापर करतो.", d3: "3. सुरक्षा", p3: "तुमची वैयक्तिक माहिती आमच्या सर्व्हरवर सुरक्षित राहील याची खात्री करण्यासाठी आम्ही उद्योग-मानक सुरक्षा उपाय वापरतो." },
      terms: { title: "सेवा अटी", t1: "1. अटींची स्वीकृती", p1: "कृषी सार्थी अनुप्रयोग वापरून, तुम्ही या सेवा अटींना सहमती देता. जर तुम्ही सहमत नसाल, तर कृपया आमच्या सेवा वापरू नका.", t2: "2. सेवेचा वापर", p2: "आमचे AI मॉडेल प्रतिमा विश्लेषणावर आधारित शिफारसी देतात. अत्यंत अचूक असले तरी, ते व्यावसायिक कृषी मूल्यांकनाचा पर्याय नाहीत. AI च्या चुकीच्या निदानामुळे होणाऱ्या पिकांच्या नुकसानीस आम्ही जबाबदार नाही.", t3: "3. वापरकर्ता आचरण", p3: "असंबंधित प्रतिमा सबमिट करून, तज्ञांच्या सल्लामसलती स्पॅम करून किंवा आमच्या सुरक्षिततेचे उल्लंघन करण्याचा प्रयत्न करून सेवेचा गैरवापर न करण्यास तुम्ही सहमत आहात." }
    }
  },
  hi: {
    translation: {
      nav: { home: "होम", about: "हमारे बारे में", features: "विशेषताएं", howItWorks: "यह कैसे काम करता है", diseases: "बीमारियां", testimonials: "प्रशंसापत्र", download: "ऐप डाउनलोड करें" },
      hero: { tag: "✨ खेती का भविष्य", title1: "आधुनिक किसानों के लिए", title2: "स्मार्ट AI", desc: "कृषि सार्थी AI ऐप के साथ तुरंत फसल की बीमारियों का पता लगाएं, विशेषज्ञ उपचार प्राप्त करें, और अपने खेत को स्मार्ट तरीके से प्रबंधित करें। भारतीय किसानों के लिए डिज़ाइन किया गया।", downloadBtn: "ऐप डाउनलोड करें", learnBtn: "और जानें", stats: { farmers: "किसान", accuracy: "सटीकता", crops: "फसलें" } },
      features: { tag: "शक्तिशाली विशेषताएं", title: "बेहतर विकास के लिए आपको जो कुछ भी चाहिए", desc: "कृषि सार्थी विशेष रूप से किसानों को उपज बढ़ाने और नुकसान कम करने में मदद करने के लिए बुद्धिमान उपकरणों से भरा हुआ है।", items: { scanTitle: "AI फसल स्कैनिंग", scanDesc: "बीमार पत्ते की एक तस्वीर लें और तुरंत बीमारी का नाम, गंभीरता और सटीक उपचार सिफारिशें प्राप्त करें।", expertTitle: "विशेषज्ञ प्रश्नोत्तर", expertDesc: "सीधे कृषि विशेषज्ञों से जुड़ें। प्रश्न पूछें, तस्वीरें साझा करें, और व्यक्तिगत खेती की सलाह प्राप्त करें।", weatherTitle: "स्मार्ट मौसम पूर्वानुमान", weatherDesc: "बुवाई, सिंचाई और कटाई की योजना बनाने में आपकी मदद करने के लिए आपके खेत के लिए अति-स्थानीय मौसम पूर्वानुमान।", fertTitle: "उर्वरक गाइड", fertDesc: "अपनी विशिष्ट फसल और मिट्टी के प्रकार के लिए आवश्यक NPK और सूक्ष्म पोषक तत्वों की सटीक मात्रा की गणना करें।", alertTitle: "समय पर अलर्ट", alertDesc: "मौसम की चेतावनियों, अपने क्षेत्र में बीमारी के प्रकोप और छिड़काव अनुस्मारकों के लिए पुश सूचनाएँ प्राप्त करें।", secTitle: "सुरक्षित और निजी", secDesc: "आपका कृषि डेटा एन्क्रिप्टेड और सुरक्षित है। हम आपकी गोपनीयता का सम्मान करते हैं और डेटा का उपयोग केवल आपकी उपज में सुधार के लिए करते हैं।" } },
      hiw: { tag: "सरल प्रक्रिया", title: "कृषि सार्थी कैसे काम करता है", desc: "फसल की बीमारियों का पता लगाना इतना आसान कभी नहीं रहा। बस एक तस्वीर लें और हमारे AI को आपके लिए भारी काम करने दें।", s1t: "स्कैनर खोलें", s1d: "कृषि सार्थी ऐप लॉन्च करें और अपने डैशबोर्ड से AI स्कैन बटन पर टैप करें।", s2t: "एक तस्वीर लें", s2d: "संक्रमित फसल के पत्ते पर अपना कैमरा इंगित करें। सुनिश्चित करें कि पत्ता स्पष्ट रूप से दिखाई दे रहा है और फोकस में है।", s3t: "त्वरित विश्लेषण प्राप्त करें", s3d: "हमारा AI तुरंत छवि का विश्लेषण करता है, बीमारी की पहचान करता है, और एक गंभीरता स्कोर प्रदान करता है।", s4t: "उपचार लागू करें", s4d: "अपनी फसल को बचाने और उपज में सुधार करने के लिए अनुशंसित जैविक या रासायनिक उपचार योजनाओं का पालन करें।" },
      diseases: { tag: "फसल लाइब्रेरी", title: "सामान्य बीमारियां जिनका हम पता लगाते हैं", desc: "हमारे AI मॉडल को 30+ फसलों में 100+ से अधिक बीमारियों की सटीक पहचान करने के लिए लाखों छवियों पर प्रशिक्षित किया गया है।", btn: "पूरी लाइब्रेरी देखें", learn: "उपचार सीखें" },
      testimonials: { tag: "हजारों किसानों का भरोसा", title: "किसान क्या कहते हैं", desc: "50,000 से अधिक किसानों से जुड़ें जो अपनी फसलों की रक्षा करने और अपनी आय बढ़ाने के लिए कृषि सार्थी पर भरोसा करते हैं।", reviews: [{name: "रमेश पाटिल", loc: "महाराष्ट्र", text: "कृषि सार्थी ऐप ने इस साल मेरी टमाटर की फसल बचा ली। मैंने बीमार पत्ते की तस्वीर ली और इसने तुरंत मुझे बताया कि यह अर्ली ब्लाइट था और मुझे सटीक दवा का नाम दिया। अत्यधिक अनुशंसित!"},{name: "सुरेश कुमार", loc: "पंजाब", text: "उर्वरक गाइड अद्भुत है। अनुमान लगाने के बजाय, अब मुझे ठीक से पता है कि अपने गेहूं के खेत के लिए कितना यूरिया और डीएपी का उपयोग करना है। मेरी उपज में 20% की वृद्धि हुई है!"},{name: "अनिल देशमुख", loc: "गुजरात", text: "ऐप से सीधे विशेषज्ञों से प्रश्न पूछना सबसे अच्छी विशेषता है। डॉक्टर जल्दी से व्यावहारिक समाधान देते हैं जो वास्तव में खेत में काम करते हैं।"}] },
      cta: { title: "अपनी खेती को बदलने के लिए तैयार हैं?", desc: "आज ही कृषि सार्थी ऐप डाउनलोड करें और अपनी फसल की उपज बढ़ाने के लिए AI का लाभ उठाने वाले आधुनिक किसानों के समुदाय में शामिल हों।", btn1: "अभी ऐप डाउनलोड करें", btn2: "विशेषज्ञ से संपर्क करें" },
      footer: { desc: "आर्टिफिशियल इंटेलिजेंस के साथ आधुनिक भारतीय किसान को सशक्त बनाना। आपकी जेब में स्मार्ट रोग का पता लगाना, मौसम के अपडेट और विशेषज्ञ खेती की सलाह।", prod: "उत्पाद", comp: "कंपनी", legal: "कानूनी", f1: "विशेषताएं", f2: "यह कैसे काम करता है", f3: "फसल लाइब्रेरी", f4: "मूल्य निर्धारण", c1: "हमारे बारे में", c2: "करियर", c3: "संपर्क करें", c4: "साझेदार", l1: "गोपनीयता नीति", l2: "सेवा की शर्तें", l3: "कुकी नीति", copy: "कृषि सार्थी AI. सर्वाधिकार सुरक्षित।" },
      about: { tag: "हमारा लक्ष्य", title: "आधुनिक किसान को सशक्त बनाना", desc: "कृषि सार्थी एक ही लक्ष्य के साथ बनाया गया था: भारत के हर किसान की उंगलियों पर विश्व स्तरीय कृषि AI तकनीक लाना। हमारा मानना है कि तकनीक सुलभ और सस्ती होनी चाहिए।", cards: [{title: "सतत खेती", desc: "जैविक समाधान और इष्टतम उर्वरक उपयोग को बढ़ावा देना।"}, {title: "डेटा सुरक्षा", desc: "आपका कृषि डेटा एन्क्रिप्टेड और पूरी तरह से निजी है।"}, {title: "विशेषज्ञ समुदाय", desc: "आपको प्रमाणित कृषि वैज्ञानिकों से जोड़ना।"}] },
      pricing: { tag: "मूल्य निर्धारण", title: "सरल, पारदर्शी मूल्य निर्धारण", desc: "मुफ्त में शुरू करें और जब आपको अधिक उन्नत AI टूल और विशेषज्ञ परामर्श की आवश्यकता हो तो अपग्रेड करें।", basic: { name: "मूल योजना", desc: "छोटे पैमाने के किसानों के लिए बिल्कुल सही।", f1: "प्रति माह 5 AI फसल स्कैन", f2: "बुनियादी मौसम अलर्ट", f3: "केवल समुदाय पहुंच", btn: "मुफ्त में शुरू करें" }, pro: { name: "प्रो किसान", desc: "व्यावसायिक खेती और अधिकतम उपज के लिए।", f1: "असीमित AI स्कैन", f2: "प्रीमियम मौसम और कीट अलर्ट", f3: "सीधा विशेषज्ञ परामर्श (वॉयस/वीडियो)", f4: "उर्वरक कैलकुलेटर", btn: "प्रो में अपग्रेड करें", rec: "अनुशंसित" } },
      contact: { title: "संपर्क करें", name: "नाम", email: "ईमेल", msg: "संदेश", btn: "संदेश भेजें" },
      privacy: { title: "गोपनीयता नीति", d1: "1. डेटा संग्रह", p1: "हम AI विश्लेषण के लिए आपके द्वारा सबमिट की गई फसलों की छवियां एकत्र करते हैं। इन छवियों को सुरक्षित रूप से संसाधित किया जाता है और फसल की बीमारियों की पहचान करने के लिए सख्ती से उपयोग किया जाता है।", d2: "2. डेटा उपयोग", p2: "आपका डेटा कभी भी तीसरे पक्ष को बेचा नहीं जाता है। हम अपने AI मॉडल को बेहतर बनाने और सटीक कृषि अंतर्दृष्टि प्रदान करने के लिए फसल डेटा का गुमनाम रूप से उपयोग करते हैं।", d3: "3. सुरक्षा", p3: "हम यह सुनिश्चित करने के लिए उद्योग-मानक सुरक्षा उपायों का उपयोग करते हैं कि आपकी व्यक्तिगत जानकारी हमारे सर्वर पर सुरक्षित रहे।" },
      terms: { title: "सेवा की शर्तें", t1: "1. शर्तों की स्वीकृति", p1: "कृषि सार्थी एप्लिकेशन का उपयोग करके, आप इन सेवा की शर्तों से सहमत होते हैं। यदि आप सहमत नहीं हैं, तो कृपया हमारी सेवाओं का उपयोग न करें।", t2: "2. सेवा का उपयोग", p2: "हमारे AI मॉडल छवि विश्लेषण के आधार पर सिफारिशें प्रदान करते हैं। अत्यधिक सटीक होने पर भी, वे पेशेवर कृषि मूल्यांकन का विकल्प नहीं हैं। हम AI के गलत निदान के परिणामस्वरूप होने वाले फसल के नुकसान के लिए उत्तरदायी नहीं हैं।", t3: "3. उपयोगकर्ता आचरण", p3: "आप अप्रासंगिक चित्र सबमिट करके, विशेषज्ञ परामर्श स्पैमिंग, या हमारी सुरक्षा का उल्लंघन करने का प्रयास करके सेवा का दुरुपयोग नहीं करने के लिए सहमत हैं।" }
    }
  }
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: "en",
    fallbackLng: "en",
    interpolation: {
      escapeValue: false
    }
  });

export default i18n;
